const Map<String, Map<String, double>> cityPercentages = {
  'New York': {
    'Food': 25.0,
    'Entertainment': 15.0,
    'Loans': 30.0,
    'Transportation': 10.0,
    'Utilities': 8.0,
    'Savings': 12.0,
  },
  'Los Angeles': {
    'Food': 22.0,
    'Entertainment': 18.0,
    'Loans': 28.0,
    'Transportation': 15.0,
    'Utilities': 7.0,
    'Savings': 10.0,
  },
  'London': {
    'Food': 20.0,
    'Entertainment': 12.0,
    'Loans': 35.0,
    'Transportation': 15.0,
    'Utilities': 10.0,
    'Savings': 8.0,
  },
  'Manchester': {
    'Food': 24.0,
    'Entertainment': 10.0,
    'Loans': 30.0,
    'Transportation': 12.0,
    'Utilities': 12.0,
    'Savings': 12.0,
  },
  'Mumbai': {
    'Food': 30.0,
    'Entertainment': 10.0,
    'Loans': 25.0,
    'Transportation': 15.0,
    'Utilities': 8.0,
    'Savings': 12.0,
  },
  'Delhi': {
    'Food': 28.0,
    'Entertainment': 8.0,
    'Loans': 22.0,
    'Transportation': 18.0,
    'Utilities': 10.0,
    'Savings': 14.0,
  },
  'Toronto': {
    'Food': 23.0,
    'Entertainment': 14.0,
    'Loans': 32.0,
    'Transportation': 12.0,
    'Utilities': 9.0,
    'Savings': 10.0,
  },
  'Sydney': {
    'Food': 21.0,
    'Entertainment': 16.0,
    'Loans': 33.0,
    'Transportation': 11.0,
    'Utilities': 8.0,
    'Savings': 11.0,
  },
};

const Map<String, List<String>> countryCityMap = {
  'United States': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
  'United Kingdom': ['London', 'Manchester', 'Birmingham', 'Liverpool'],
  'Canada': ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'],
  'Australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth'],
  'Germany': ['Berlin', 'Munich', 'Hamburg', 'Frankfurt'],
  'France': ['Paris', 'Lyon', 'Marseille', 'Toulouse'],
  'India': ['Mumbai', 'Delhi', 'Bangalore', 'Chennai'],
  'Japan': ['Tokyo', 'Osaka', 'Kyoto', 'Nagoya'],
  'Singapore': ['Singapore'],
  'Netherlands': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht'],
};

const Map<String, List<String>> countryCurrencyMap = {
  'United States': ['USD'],
  'United Kingdom': ['GBP'],
  'Canada': ['CAD'],
  'Australia': ['AUD'],
  'Germany': ['EUR'],
  'France': ['EUR'],
  'India': ['INR'],
  'Japan': ['JPY'],
  'Singapore': ['SGD'],
  'Netherlands': ['EUR'],
};
